apiVersion: v1
kind: Namespace
metadata:
  name: pwc-task-namespace # Replace with your desired namespace name
  labels:
    environment: development # Optional: Add labels for organization
    # Enforce Restricted Pod Security Standard
    # This label ensures that pods in this namespace adhere to the restricted PSP profile,
    # which provides strong hardening for your workloads.
    pod-security.kubernetes.io/enforce: restricted
---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: pwc-resource-quota # Name for the resource quota
  namespace: pwc-task-namespace # Must match the namespace name above
spec:
  hard:
    # CPU limits:
    limits.cpu: "2" # Total CPU limits for all pods in the namespace (e.g., 2 cores)
    requests.cpu: "1" # Total CPU requests for all pods in the namespace (e.g., 1 core)

    # Memory limits:
    limits.memory: "4Gi" # Total memory limits for all pods in the namespace (e.g., 4 Gigabytes)
    requests.memory: "2Gi" # Total memory requests for all pods in the namespace (e.g., 2 Gigabytes)
