apiVersion: v1
kind: Service
metadata:
  name: microservices-app-internal-service 
  namespace: pwc-task-namespace 
  labels:
    app: microservices-app
  annotations:
    # Azure-specific annotation to create an internal Load Balancer
    # This ensures the Load Balancer gets a private IP address and is not exposed to the internet.
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: microservices-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000